// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortTraining(arg1) {
  return window['go']['main']['App']['AbortTraining'](arg1);
}

export function AddAgentConfig(arg1) {
  return window['go']['main']['App']['AddAgentConfig'](arg1);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AddStocksToWatchlist(arg1) {
  return window['go']['main']['App']['AddStocksToWatchlist'](arg1);
}

export function AddStrategy(arg1) {
  return window['go']['main']['App']['AddStrategy'](arg1);
}

export function AddToWatchlist(arg1) {
  return window['go']['main']['App']['AddToWatchlist'](arg1);
}

export function CancelInterruptedMeeting(arg1) {
  return window['go']['main']['App']['CancelInterruptedMeeting'](arg1);
}

export function CancelMeeting(arg1) {
  return window['go']['main']['App']['CancelMeeting'](arg1);
}

export function CancelSelector() {
  return window['go']['main']['App']['CancelSelector']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearSessionMessages(arg1) {
  return window['go']['main']['App']['ClearSessionMessages'](arg1);
}

export function CreateTrainingSession() {
  return window['go']['main']['App']['CreateTrainingSession']();
}

export function DeleteAgentConfig(arg1) {
  return window['go']['main']['App']['DeleteAgentConfig'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteSelectorRecord(arg1, arg2) {
  return window['go']['main']['App']['DeleteSelectorRecord'](arg1, arg2);
}

export function DeleteStrategy(arg1) {
  return window['go']['main']['App']['DeleteStrategy'](arg1);
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function EnhancePrompt(arg1) {
  return window['go']['main']['App']['EnhancePrompt'](arg1);
}

export function ExecuteTrainingTrade(arg1) {
  return window['go']['main']['App']['ExecuteTrainingTrade'](arg1);
}

export function GenerateStrategy(arg1) {
  return window['go']['main']['App']['GenerateStrategy'](arg1);
}

export function GetActiveStrategyID() {
  return window['go']['main']['App']['GetActiveStrategyID']();
}

export function GetAgentConfigs() {
  return window['go']['main']['App']['GetAgentConfigs']();
}

export function GetAllHotTrends() {
  return window['go']['main']['App']['GetAllHotTrends']();
}

export function GetAllMilestones() {
  return window['go']['main']['App']['GetAllMilestones']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetBestTrainingRecord() {
  return window['go']['main']['App']['GetBestTrainingRecord']();
}

export function GetBoardFundFlow(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBoardFundFlow'](arg1, arg2, arg3);
}

export function GetBoardLeaders(arg1, arg2) {
  return window['go']['main']['App']['GetBoardLeaders'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetF10Overview(arg1) {
  return window['go']['main']['App']['GetF10Overview'](arg1);
}

export function GetF10Valuation(arg1) {
  return window['go']['main']['App']['GetF10Valuation'](arg1);
}

export function GetHotTrend(arg1) {
  return window['go']['main']['App']['GetHotTrend'](arg1);
}

export function GetHotTrendPlatforms() {
  return window['go']['main']['App']['GetHotTrendPlatforms']();
}

export function GetKLineData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetKLineData'](arg1, arg2, arg3);
}

export function GetLongHuBangDetail(arg1, arg2) {
  return window['go']['main']['App']['GetLongHuBangDetail'](arg1, arg2);
}

export function GetLongHuBangList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLongHuBangList'](arg1, arg2, arg3);
}

export function GetMCPServerTools(arg1) {
  return window['go']['main']['App']['GetMCPServerTools'](arg1);
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMarketIndices() {
  return window['go']['main']['App']['GetMarketIndices']();
}

export function GetMarketStatus() {
  return window['go']['main']['App']['GetMarketStatus']();
}

export function GetMilestoneInfo(arg1) {
  return window['go']['main']['App']['GetMilestoneInfo'](arg1);
}

export function GetOpenClawStatus() {
  return window['go']['main']['App']['GetOpenClawStatus']();
}

export function GetOrCreateSession(arg1, arg2) {
  return window['go']['main']['App']['GetOrCreateSession'](arg1, arg2);
}

export function GetOrderBook(arg1) {
  return window['go']['main']['App']['GetOrderBook'](arg1);
}

export function GetSelectorCacheStats() {
  return window['go']['main']['App']['GetSelectorCacheStats']();
}

export function GetSelectorRecords() {
  return window['go']['main']['App']['GetSelectorRecords']();
}

export function GetSelectorRecordsByDate(arg1) {
  return window['go']['main']['App']['GetSelectorRecordsByDate'](arg1);
}

export function GetSelectorStrategies() {
  return window['go']['main']['App']['GetSelectorStrategies']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetStockMoves(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockMoves'](arg1, arg2, arg3);
}

export function GetStockRealTimeData(arg1) {
  return window['go']['main']['App']['GetStockRealTimeData'](arg1);
}

export function GetStrategies() {
  return window['go']['main']['App']['GetStrategies']();
}

export function GetTelegraphList() {
  return window['go']['main']['App']['GetTelegraphList']();
}

export function GetTradeDates(arg1) {
  return window['go']['main']['App']['GetTradeDates'](arg1);
}

export function GetTradingSchedule() {
  return window['go']['main']['App']['GetTradingSchedule']();
}

export function GetTrainingCapitalCurve(arg1) {
  return window['go']['main']['App']['GetTrainingCapitalCurve'](arg1);
}

export function GetTrainingKlines(arg1) {
  return window['go']['main']['App']['GetTrainingKlines'](arg1);
}

export function GetTrainingPrediction(arg1) {
  return window['go']['main']['App']['GetTrainingPrediction'](arg1);
}

export function GetTrainingRecords() {
  return window['go']['main']['App']['GetTrainingRecords']();
}

export function GetTrainingSession(arg1) {
  return window['go']['main']['App']['GetTrainingSession'](arg1);
}

export function GetTrainingStats(arg1) {
  return window['go']['main']['App']['GetTrainingStats'](arg1);
}

export function GetTrainingTrades(arg1) {
  return window['go']['main']['App']['GetTrainingTrades'](arg1);
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsSelectorRunning() {
  return window['go']['main']['App']['IsSelectorRunning']();
}

export function NextTrainingDay(arg1) {
  return window['go']['main']['App']['NextTrainingDay'](arg1);
}

export function NotifyFrontendReady() {
  return window['go']['main']['App']['NotifyFrontendReady']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['main']['App']['RemoveFromWatchlist'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RetryAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryAgent'](arg1, arg2, arg3);
}

export function RetryAgentAndContinue(arg1) {
  return window['go']['main']['App']['RetryAgentAndContinue'](arg1);
}

export function RunSelector(arg1) {
  return window['go']['main']['App']['RunSelector'](arg1);
}

export function SaveSelectorRecord(arg1) {
  return window['go']['main']['App']['SaveSelectorRecord'](arg1);
}

export function SearchStocks(arg1) {
  return window['go']['main']['App']['SearchStocks'](arg1);
}

export function SendMeetingMessage(arg1) {
  return window['go']['main']['App']['SendMeetingMessage'](arg1);
}

export function SetActiveStrategy(arg1) {
  return window['go']['main']['App']['SetActiveStrategy'](arg1);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function TestMCPConnection(arg1) {
  return window['go']['main']['App']['TestMCPConnection'](arg1);
}

export function UpdateAgentConfig(arg1) {
  return window['go']['main']['App']['UpdateAgentConfig'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}

export function UpdateStockPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStockPosition'](arg1, arg2, arg3);
}

export function UpdateStrategy(arg1) {
  return window['go']['main']['App']['UpdateStrategy'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
